### ISSUE TITLE
Checkbox-based consent frame for ManyBabies-AtHome

### ISSUE THREAD

**Issue by kimberscott** [lookit/ember-lookit-frameplayer#225]
**Is your feature request related to a problem? Please describe.**
ManyBabies-AtHome needs to avoid storing ANY video data, including the consent recording, prior to having confirmed consent.

**Is your feature request related to a particular frame?**
exp-lookit-video-consent

**Describe your idea or solution**
A new consent frame where the parent reads the document and then answers a series of yes/no (or checkbox) questions/statements, rather than making a recording. It's only possible to proceed if certain answers are "correct" (e.g. if they do agree to participate). All answers are stored as frame data. 

**Describe alternatives you've considered**
We'd like to avoid this becoming the default because it isn't as good a guarantee that the parent really understands they're being recorded and that they can read the language the consent form is in. However, we haven't found any workarounds for MBAH purposes.

**Implementation steps**
- [x] Create blank component with "submit" button
- [x] Structure input (list of items of type text-block, checkbox, multiple-choice) and create example for local testing
- [x] Implement text-block option
- [x] Implement checkbox option
- [x] Implement multiple-choice option
- [x] Store all data
- [x] Allow labeling of questions (with input validation)
- [x] Make questions required and display warning text
- [x] Documentation
- [x] Basic test of rendering
- [x] Test that any unchecked checkboxes -> unable to proceed
- [x] Test that any unselected multiple-choice questions -> unable to proceed
- [x] Test that if questions are given duplicate or invalid labels these are replaced appropriately
- [x] Test that if all questions are answered, can proceed & appropriate data is saved for the frame

**Additional context**
Confirming consent may require the researcher to "approve" each record, even though they'll all by definition have consented if they completed the frame.

**Comment by kimberscott** [comment]
Transferring notes from email. From Lorijn Zaadnoordijk:

Our main concern with the current consent procedure is that identifiable (video) data will be stored on US servers regardless of whether valid consent has been obtained. I understand that for your legal team, the deciding factor is whether or not you look at the videos, but from our point of view (e.g., data protection regulations in Europe, GDPR), it is already problematic that data will be recorded and stored on (US) commercial cloud servers without consent. The IRBs and Data Protection Officers, at least in Europe, will have difficulties accepting it from an ethical or legal perspective. We are not allowed to acquire data before we know consent has been given (even questionnaires need a response-sensitive question that either skips sensitive content or ensures no data is being collected). We further need consent to store  data in the commercial cloud outside Europe (with the US being a particularly sensitive topic due to the difficulty implementing the right to be forgotten and the access government agencies have to the data, in principle). The current LookIt setup does thus three things that are not strictly speaking legal under GDPR: 1. collect sensitive data (videos) before consent has been verified (and, thus, in certain cases without consent), 2. store sensitive data outside Europe where 3. we cannot ensure nobody accesses it and it cannot be permanently removed (i.e. we need assurances from AWS, which as far as we are aware have not been given, yet). There is also a fourth problem: If the translators had to vet the videos beforehand for the consent, the legal problem would not only remain but in fact get worse as there would be a larger group of people who would have access to identifiable data that has been recorded without consent. 

We recognize your concern about parents possibly not reading the consent form properly before ticking some box, so we would like to suggest having a consent form with a yes/no tick box after each statement. The benefit is that parents have to read only 1 or 2 sentences per tick box (which has explicit yes or no options), which they will be more likely to do, and that we can ask for more nuanced consent. Certain boxes must be ticked to be eligible for participation, but other boxes (e.g., agreeing to having their identifiable data used for educational or publicity purposes) can be optional. If they forget to tick a box (i.e. agreeing or not agreeing), we can remind them that their consent isn’t valid yet and catch any issues before the experiment (and thus the video recording) starts. I have attached an example that we have been required to use at TCD. The exact wording would have to be different for LookIt and I would personally prefer for it to be a bit shorter, so there is definitely still flexibility regarding the exact form, I just wanted to provide you with an example.

> I would recommend that the webcam be visible in this frame (kind of like this where the participant checks off some setup steps) just to help make it salient that there will be recording later if they agree.

Yes, we will absolutely do that. We will want to instruct people on how to best position themselves in front of the webcam in any case, so making very clear in the process that they will be recorded by having them check off the setup steps should be no problem.

**Comment by kimberscott** [comment]
Note: promised by May 2021, ideally waiting on concrete text proposal to ground design
